package com.ryulth.woom.domain.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted
import com.ryulth.woom.util.LocalDateTimeDynamoDBConverter
import java.time.LocalDateTime
import org.springframework.data.annotation.Transient

/**
 * DynamoDB lib 안에서 uuid id 를 사용할 때 generated 한 값을 invoke 시킬떄 setter가 필요하다
 */
@DynamoDBTable(tableName = "Message")
data class Message(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String = "",

    @DynamoDBAttribute
    var chatRoomId: Long = 0,

    @DynamoDBAttribute
    var authorId: Long = 0,

    @DynamoDBAttribute
    var brokerChannel: String = "",

    @DynamoDBAttribute
    var sequenceNo: Long = 0,

    @DynamoDBAttribute
    var content: String = "",

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeDynamoDBConverter::class)
    var createdAt: LocalDateTime = LocalDateTime.now()
) {
    /**
     * id generated 를 위한 key string
     */
    companion object {
        @Transient
        val SEQUENCE_NAME = "messageSequence"
    }
}
