package com.ryulth.woom.domain.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted
import com.ryulth.woom.util.LocalDateTimeDynamoDBConverter
import org.springframework.data.annotation.Transient
import java.time.LocalDateTime

/**
 * DynamoDB lib 안에서 uuid id 를 사용할 때 generated 한 값을 invoke 시킬떄 setter가 필요하다
 */
@DynamoDBTable(tableName = "Message")
data class Message (
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBRangeKey
    @DynamoDBAttribute
    val chatRoomId: Long,

    @DynamoDBAttribute
    val authorId: Long,

    @DynamoDBAttribute
    val brokerChannel: String,

    @DynamoDBAttribute
    val sequenceNo: Long,

    @DynamoDBAttribute
    val content: String,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeDynamoDBConverter::class)
    var createdAt: LocalDateTime = LocalDateTime.now()
) {
    /**
     * id generated 를 위한 key string
     */
    companion object {
        @Transient
        val SEQUENCE_NAME = "messageSequence"
    }
}