package com.ryulth.woom.domain.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted
import com.ryulth.woom.util.LocalDateTimeDynamoDBConverter
import java.time.LocalDateTime

/**
 * DynamoDB lib 안에서 uuid id 를 사용할 때 generated 한 값을 invoke 시킬떄 setter가 필요하다
 */
@DynamoDBTable(tableName = "Post")
data class Post(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    val authorId: Long,

    @DynamoDBAttribute
    val title: String,

    @DynamoDBAttribute
    val content: String,

    @DynamoDBAttribute
    val hasCategorySet: MutableSet<String>?,

    @DynamoDBAttribute
    val wantCategorySet: MutableSet<String>?,

    @DynamoDBAttribute
    val location: String,

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeDynamoDBConverter::class)
    val createdAt: LocalDateTime = LocalDateTime.now()
)
